from collections.abc import Callable, Sequence
from typing import Any, BinaryIO, Dict, IO, List, TextIO, Tuple, Union

# Type aliases
TimerCallback = Callable[[int], Any]
FileDescriptorCallback = Callable[[int], Any]
HttpCallback = Callable[[int, str, str, bool, str], Any]


class MemoryStream:
    def __init__(self) -> None: ...
    def append(self, dataType: str, value: Any) -> None: ...
    def pop(self, dataType: str) -> Any: ...
    def __bytes__(self) -> bytes: ...

LOG_TYPE_NORMAL: int
LOG_TYPE_INFO: int
LOG_TYPE_ERR: int
LOG_TYPE_DBG: int
LOG_TYPE_WAR: int
NEXT_ONLY: int

component: str


def publish() -> int: ...
def scriptLogType(logType: int) -> None: ...
def getResFullPath(res: str) -> str: ...
def hasRes(res: str) -> bool: ...
def open(res: str, mode: str = "r") -> Union[IO[Any], TextIO, BinaryIO]: ...
def listPathRes(path: str, extension: Union[str, Sequence[str]] = "") -> Tuple[str, ...]: ...
def matchPath(res: str) -> str: ...
def debugTracing() -> None: ...
def genUUID64() -> int: ...
def addTimer(initialOffset: float, repeatOffset: float, callbackObj: TimerCallback) -> int: ...
def delTimer(id: int) -> int: ...
def registerReadFileDescriptor(fileDescriptor: int, callback: FileDescriptorCallback) -> None: ...
def registerWriteFileDescriptor(fileDescriptor: int, callback: FileDescriptorCallback) -> None: ...
def deregisterReadFileDescriptor(fileDescriptor: int) -> None: ...
def deregisterWriteFileDescriptor(fileDescriptor: int) -> None: ...
def urlopen(
    url: str,
    callback: Union[HttpCallback, None] = None,
    postData: Union[bytes, None] = None,
    headers: Union[Dict[str, str], None] = None
) -> None: ...
