from __future__ import annotations

from collections.abc import Callable
from typing import Any, TypeAlias, overload

from _KBEngine_common import Vector3Like, WatcherValue

EntityEventCallback: TypeAlias = Callable[..., Any]
BotCallback: TypeAlias = Callable[[], Any]
HttpCallback: TypeAlias = Callable[[int, str, str, bool, str], Any]

LOG_TYPE_NORMAL: int
LOG_TYPE_INFO: int
LOG_TYPE_ERR: int
LOG_TYPE_DBG: int
LOG_TYPE_WAR: int

component: str


class Entity:
    id: int
    className: str
    spaceID: int
    position: Vector3Like
    direction: Vector3Like
    isOnGround: bool
    inWorld: bool

    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def baseCall(self, methodName: str, *methodArgs: Any) -> None: ...
    def cellCall(self, methodName: str, *methodArgs: Any) -> None: ...
    def isPlayer(self) -> bool: ...
    def getComponent(self, componentName: str, all: bool = False) -> Any: ...
    def fireEvent(self, eventName: str, *args: Any) -> None: ...
    def registerEvent(self, eventName: str, callback: EntityEventCallback) -> None: ...
    def deregisterEvent(self, eventName: str, callback: EntityEventCallback) -> None: ...


class EntityComponent:
    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def fireEvent(self, eventName: str, *args: Any) -> None: ...
    def registerEvent(self, eventName: str, callback: EntityEventCallback) -> None: ...
    def deregisterEvent(self, eventName: str, callback: EntityEventCallback) -> None: ...


class Entities(dict[int, Entity]):
    pass


class ClientObject:
    id: int
    entities: Entities

    def player(self) -> Entity | None: ...
    def getSpaceData(self, key: str) -> str: ...
    def callback(self, initialOffset: float, callbackObj: BotCallback) -> int: ...
    def cancelCallback(self, id: int) -> None: ...
    def getWatcher(self, path: str) -> WatcherValue: ...
    def getWatcherDir(self, path: str) -> tuple[str, ...]: ...
    def disconnect(self, lock_secs: int = 0) -> None: ...
    def kbassert(self) -> None: ...


class PyBots(dict[int, ClientObject]):
    def has_key(self, clientID: int) -> bool: ...
    def keys(self) -> list[int]: ...
    def values(self) -> list[ClientObject]: ...
    def items(self) -> list[tuple[int, ClientObject]]: ...
    @overload
    def get(self, clientID: int) -> ClientObject | None: ...
    @overload
    def get(self, clientID: int, default: Any) -> ClientObject | Any: ...


bots: PyBots


def addBots(
    reqCreateAndLoginTotalCount: int,
    reqCreateAndLoginTickCount: int = 0,
    reqCreateAndLoginTickTime: float = 0.0
) -> None: ...
def scriptLogType(logType: int) -> None: ...
def genUUID64() -> int: ...
def urlopen(
    url: str,
    callback: HttpCallback | None = None,
    postData: bytes | None = None,
    headers: dict[str, str] | None = None
) -> None: ...
def __getattr__(name: str) -> Any: ...
