from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any, BinaryIO, IO, Literal, TextIO, TypeAlias, overload

from _KBEngine_server_errors import *

Vector3Like: TypeAlias = tuple[float, float, float] | Sequence[float]
Address: TypeAlias = Any
WatcherValue: TypeAlias = Any
Callback: TypeAlias = Callable[..., Any]


class EntityCall:
    def __getattr__(self, name: str) -> Any: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[False] = False) -> EntityComponentCall | None: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[True]) -> tuple[EntityComponentCall, ...]: ...


class BaseEntityCall(EntityCall): ...


class CellEntityCall(EntityCall): ...


class ClientEntityCall(EntityCall): ...


class EntityComponentCall(EntityCall): ...


class MemoryStream:
    def __init__(self) -> None: ...
    def append(self, dataType: str, value: Any) -> None: ...
    def pop(self, dataType: str) -> Any: ...
    def __bytes__(self) -> bytes: ...


class GlobalDataClient(dict[str, Any]):
    pass


class Entity:
    id: int
    className: str
    client: ClientEntityCall | None
    cell: CellEntityCall | None
    base: BaseEntityCall | None
    databaseID: int
    databaseInterfaceName: str
    isDestroyed: bool
    shouldAutoArchive: bool | int
    shouldAutoBackup: bool | int

    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def addTimer(self, initialOffset: float, repeatOffset: float = 0.0, userArg: int = 0) -> int: ...
    def delTimer(self, id: int | str) -> None: ...
    def destroy(self, deleteFromDB: bool = False, writeToDB: bool = False) -> None: ...
    def writeToDB(
        self,
        callback: Callback | None = None,
        shouldAutoLoad: bool = False,
        dbInterfaceName: str = "default"
    ) -> None: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[False] = False) -> EntityComponent | None: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[True]) -> tuple[EntityComponent, ...]: ...
    def fireEvent(self, eventName: str, *args: Any) -> None: ...
    def registerEvent(self, eventName: str, callback: Callback) -> None: ...
    def deregisterEvent(self, eventName: str, callback: Callback) -> None: ...
    def createCellEntity(self, cellEntityCall: CellEntityCall | None = None) -> None: ...
    def createCellEntityInNewSpace(self, cellappIndex: int = 0) -> None: ...
    def destroyCellEntity(self) -> None: ...
    def clientEntity(self, destID: int) -> ClientEntityCall: ...
    def isReal(self) -> bool: ...
    def cancelController(self, controllerID: int | str) -> None: ...
    def canNavigate(self) -> bool: ...
    def setViewRadius(self, radius: float, hyst: float = 5.0) -> None: ...
    def getViewRadius(self) -> float: ...
    def getViewHystArea(self) -> float: ...
    def entitiesInView(self, pending: bool = False) -> tuple[Entity, ...]: ...
    def entitiesInRange(
        self,
        range: float,
        entityType: str | None = None,
        position: Vector3Like | None = None
    ) -> tuple[Entity, ...]: ...
    def teleport(
        self,
        nearbyMBRef: CellEntityCall | Entity | None,
        position: Vector3Like,
        direction: Vector3Like
    ) -> None: ...
    def destroySpace(self) -> None: ...
    def debugView(self) -> None: ...
    def getWitnesses(self) -> tuple[Entity, ...]: ...


class Proxy(Entity):
    __ACCOUNT_NAME__: str
    __ACCOUNT_PASSWORD__: str
    clientAddr: Address
    clientEnabled: bool
    hasClient: bool
    roundTripTime: float
    timeSinceHeardFromClient: float

    def disconnect(self) -> None: ...
    def getClientType(self) -> int: ...
    def getClientDatas(self) -> tuple[bytes, bytes]: ...
    def giveClientTo(self, proxy: Proxy) -> None: ...
    def streamFileToClient(self, resourceName: str, desc: str = "", id: int = -1) -> int: ...
    def streamStringToClient(self, data: str | bytes, desc: str = "", id: int = -1) -> int: ...


class Space(Entity):
    pass


class EntityComponent:
    client: ClientEntityCall | None
    cell: CellEntityCall | None
    base: BaseEntityCall | None

    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def addTimer(self, initialOffset: float, repeatOffset: float = 0.0, userArg: int = 0) -> int: ...
    def delTimer(self, id: int | str) -> None: ...
    def clientEntity(self, destID: int) -> ClientEntityCall: ...


class Entities(dict[int, Entity]):
    pass


LOG_ON_ACCEPT: int
LOG_ON_REJECT: int
LOG_ON_WAIT_FOR_DESTROY: int
LOG_TYPE_NORMAL: int
LOG_TYPE_INFO: int
LOG_TYPE_ERR: int
LOG_TYPE_DBG: int
LOG_TYPE_WAR: int
NEXT_ONLY: int

component: str


def publish() -> int: ...
def scriptLogType(logType: int) -> None: ...
def getResFullPath(res: str) -> str: ...
def hasRes(res: str) -> bool: ...
def listPathRes(path: str, extension: str | tuple[str, ...] = "") -> tuple[str, ...]: ...
def matchPath(res: str) -> str: ...
def debugTracing() -> None: ...
def genUUID64() -> int: ...
def addTimer(initialOffset: float, repeatOffset: float = 0.0, callbackObj: Callable[[int], Any] | None = None) -> int: ...
def delTimer(id: int) -> None: ...
def registerReadFileDescriptor(fileDescriptor: int, callback: Callback) -> None: ...
def registerWriteFileDescriptor(fileDescriptor: int, callback: Callback) -> None: ...
def deregisterReadFileDescriptor(fileDescriptor: int) -> None: ...
def deregisterWriteFileDescriptor(fileDescriptor: int) -> None: ...
def executeRawDatabaseCommand(
    command: str,
    callback: Callback | None = None,
    threadID: int = 0,
    dbInterfaceName: str = "default"
) -> None: ...
def open(res: str, mode: str = "r", encoding: str | None = None) -> IO[Any] | TextIO | BinaryIO: ...
def accountLoginResponse(commitName: str, realAccountName: str, extraDatas: bytes, errorCode: int) -> None: ...
def createAccountResponse(commitName: str, realAccountName: str, extraDatas: bytes, errorCode: int) -> None: ...
def chargeResponse(orderID: str, extraDatas: bytes, errorCode: int) -> None: ...
def urlopen(
    url: str,
    callback: Callback | None = None,
    postData: bytes | None = None,
    headers: dict[str, str] | None = None
) -> None: ...
def __getattr__(name: str) -> Any: ...
