from __future__ import annotations

from collections.abc import Callable
from typing import Any

from _KBEngine_common import Address, Entities, Entity, GlobalDataClient, Vector3Like, WatcherValue

entities: Entities
globalData: GlobalDataClient
cellAppData: GlobalDataClient


def address() -> Address: ...
def time() -> int: ...
def isShuttingDown() -> bool: ...
def getWatcher(path: str) -> WatcherValue: ...
def getWatcherDir(path: str) -> tuple[str, ...]: ...
def addWatcher(path: str, dataType: str, getFunction: Callable[[], WatcherValue]) -> None: ...
def delWatcher(path: str) -> None: ...
def setAppFlags(flags: int) -> None: ...
def getAppFlags() -> int: ...
def reloadScript(fullReload: bool = False) -> None: ...
def createEntity(
    entityType: str,
    spaceID: int,
    position: Vector3Like,
    direction: Vector3Like,
    params: dict[str, Any] | None = None
) -> Entity | None: ...
def addSpaceGeometryMapping(
    spaceID: int,
    mapper: Any = None,
    path: str = "",
    shouldLoadOnServer: bool = True,
    params: dict[int, str] | None = None
) -> None: ...
def getSpaceGeometryMapping(spaceID: int) -> str: ...
def setSpaceData(spaceID: int, key: str, value: str) -> None: ...
def getSpaceData(spaceID: int, key: str) -> str: ...
def delSpaceData(spaceID: int, key: str) -> None: ...
def raycast(spaceID: int, layer: int, src: Vector3Like, dst: Vector3Like) -> Any: ...
