from collections.abc import Callable, Sequence
from typing import Any, BinaryIO, Dict, IO, List, TextIO, Tuple, Union, overload

try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal

from _KBEngine_server_errors import *

# Type aliases
Vector3Like = Union[Tuple[float, float, float], Sequence[float]]
Address = Any
WatcherValue = Any
Callback = Callable[..., Any]


class EntityCall:
    def __getattr__(self, name: str) -> Any: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[False] = False) -> Union[EntityComponentCall, None]: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[True]) -> Tuple[EntityComponentCall, ...]: ...


class BaseEntityCall(EntityCall): ...


class CellEntityCall(EntityCall): ...


class ClientEntityCall(EntityCall): ...


class EntityComponentCall(EntityCall): ...


class MemoryStream:
    def __init__(self) -> None: ...
    def append(self, dataType: str, value: Any) -> None: ...
    def pop(self, dataType: str) -> Any: ...
    def __bytes__(self) -> bytes: ...


class GlobalDataClient(Dict[str, Any]):
    pass


class Entity:
    id: int
    className: str
    client: Union[ClientEntityCall, None]
    cell: Union[CellEntityCall, None]
    base: Union[BaseEntityCall, None]
    databaseID: int
    databaseInterfaceName: str
    isDestroyed: bool
    shouldAutoArchive: Union[bool, int]
    shouldAutoBackup: Union[bool, int]

    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def addTimer(self, initialOffset: float, repeatOffset: float = 0.0, userArg: int = 0) -> int: ...
    def delTimer(self, id: Union[int, str]) -> None: ...
    def destroy(self, deleteFromDB: bool = False, writeToDB: bool = False) -> None: ...
    def writeToDB(
        self,
        callback: Union[Callback, None] = None,
        shouldAutoLoad: bool = False,
        dbInterfaceName: str = "default"
    ) -> None: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[False] = False) -> Union[EntityComponent, None]: ...
    @overload
    def getComponent(self, componentName: str, all: Literal[True]) -> Tuple[EntityComponent, ...]: ...
    def fireEvent(self, eventName: str, *args: Any) -> None: ...
    def registerEvent(self, eventName: str, callback: Callback) -> None: ...
    def deregisterEvent(self, eventName: str, callback: Callback) -> None: ...
    def createCellEntity(self, cellEntityCall: Union[CellEntityCall, None] = None) -> None: ...
    def createCellEntityInNewSpace(self, cellappIndex: int = 0) -> None: ...
    def destroyCellEntity(self) -> None: ...
    def clientEntity(self, destID: int) -> ClientEntityCall: ...
    def isReal(self) -> bool: ...
    def cancelController(self, controllerID: Union[int, str]) -> None: ...
    def canNavigate(self) -> bool: ...
    def setViewRadius(self, radius: float, hyst: float = 5.0) -> None: ...
    def getViewRadius(self) -> float: ...
    def getViewHystArea(self) -> float: ...
    def entitiesInView(self, pending: bool = False) -> Tuple[Entity, ...]: ...
    def entitiesInRange(
        self,
        range: float,
        entityType: Union[str, None] = None,
        position: Union[Vector3Like, None] = None
    ) -> Tuple[Entity, ...]: ...
    def teleport(
        self,
        nearbyMBRef: Union[CellEntityCall, Entity, None],
        position: Vector3Like,
        direction: Vector3Like
    ) -> None: ...
    def destroySpace(self) -> None: ...
    def debugView(self) -> None: ...
    def getWitnesses(self) -> Tuple[Entity, ...]: ...


class Proxy(Entity):
    __ACCOUNT_NAME__: str
    __ACCOUNT_PASSWORD__: str
    clientAddr: Address
    clientEnabled: bool
    hasClient: bool
    roundTripTime: float
    timeSinceHeardFromClient: float

    def disconnect(self) -> None: ...
    def getClientType(self) -> int: ...
    def getClientDatas(self) -> Tuple[bytes, bytes]: ...
    def giveClientTo(self, proxy: Proxy) -> None: ...
    def streamFileToClient(self, resourceName: str, desc: str = "", id: int = -1) -> int: ...
    def streamStringToClient(self, data: Union[str, bytes], desc: str = "", id: int = -1) -> int: ...


class Space(Entity):
    pass


class EntityComponent:
    client: Union[ClientEntityCall, None]
    cell: Union[CellEntityCall, None]
    base: Union[BaseEntityCall, None]

    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def addTimer(self, initialOffset: float, repeatOffset: float = 0.0, userArg: int = 0) -> int: ...
    def delTimer(self, id: Union[int, str]) -> None: ...
    def clientEntity(self, destID: int) -> ClientEntityCall: ...


class Entities(Dict[int, Entity]):
    pass


LOG_ON_ACCEPT: int
LOG_ON_REJECT: int
LOG_ON_WAIT_FOR_DESTROY: int
LOG_TYPE_NORMAL: int
LOG_TYPE_INFO: int
LOG_TYPE_ERR: int
LOG_TYPE_DBG: int
LOG_TYPE_WAR: int
NEXT_ONLY: int

component: str


def publish() -> int: ...
def scriptLogType(logType: int) -> None: ...
def getResFullPath(res: str) -> str: ...
def hasRes(res: str) -> bool: ...
def listPathRes(path: str, extension: Union[str, Tuple[str, ...]] = "") -> Tuple[str, ...]: ...
def matchPath(res: str) -> str: ...
def debugTracing(self) -> None: ...
def genUUID64() -> int: ...
def addTimer(initialOffset: float, repeatOffset: float = 0.0, callbackObj: Union[Callable[[int], Any], None] = None) -> int: ...
def delTimer(id: int) -> None: ...
def registerReadFileDescriptor(fileDescriptor: int, callback: Callback) -> None: ...
def registerWriteFileDescriptor(fileDescriptor: int, callback: Callback) -> None: ...
def deregisterReadFileDescriptor(fileDescriptor: int) -> None: ...
def deregisterWriteFileDescriptor(fileDescriptor: int) -> None: ...
def executeRawDatabaseCommand(
    command: str,
    callback: Union[Callback, None] = None,
    threadID: int = 0,
    dbInterfaceName: str = "default"
) -> None: ...
def open(res: str, mode: str = "r", encoding: Union[str, None] = None) -> Union[IO[Any], TextIO, BinaryIO]: ...
def accountLoginResponse(commitName: str, realAccountName: str, extraDatas: bytes, errorCode: int) -> None: ...
def createAccountResponse(commitName: str, realAccountName: str, extraDatas: bytes, errorCode: int) -> None: ...
def chargeResponse(orderID: str, extraDatas: bytes, errorCode: int) -> None: ...
def urlopen(
    url: str,
    callback: Union[Callback, None] = None,
    postData: Union[bytes, None] = None,
    headers: Union[Dict[str, str], None] = None
) -> None: ...
def __getattr__(name: str) -> Any: ...
