from typing import Any, Union

try:
    from typing import Protocol
except ImportError:
    from typing_extensions import Protocol

from _KBEngine_common import Address, Entity

class BaseAppModuleHooks(Protocol):
    def onBaseAppReady(self, isBootstrap: bool) -> None: ...
    def onReadyForLogin(self, isBootstrap: bool) -> Union[float, int]: ...
    def onReadyForShutDown(self) -> bool: ...
    def onBaseAppShutDown(self, state: int) -> None: ...
    def onInit(self, isReload: bool) -> None: ...
    def onFini(self) -> None: ...
    def onCellAppDeath(self, addr: Address) -> None: ...
    def onGlobalData(self, key: str, value: Any) -> None: ...
    def onGlobalDataDel(self, key: str) -> None: ...
    def onBaseAppData(self, key: str, value: Any) -> None: ...
    def onBaseAppDataDel(self, key: str) -> None: ...
    def onLoseChargeCB(
        self, ordersID: str, dbid: int, success: bool, datas: bytes
    ) -> None: ...
    def onAutoLoadEntityCreate(self, entityType: str, dbid: int) -> Any: ...

class CellAppModuleHooks(Protocol):
    def onInit(self, isReload: bool) -> None: ...
    def onGlobalData(self, key: str, value: Any) -> None: ...
    def onGlobalDataDel(self, key: str) -> None: ...
    def onCellAppData(self, key: str, value: Any) -> None: ...
    def onCellAppDataDel(self, key: str) -> None: ...
    def onSpaceData(self, spaceID: int, key: str, value: Any) -> None: ...
    def onAllSpaceGeometryLoaded(
        self, spaceID: int, isBootstrap: bool, mapping: Any
    ) -> None: ...

class LoginAppModuleHooks(Protocol):
    def onLoginAppReady(self) -> None: ...
    def onTick(self, timerID: int) -> None: ...
    def onLoginAppShutDown(self) -> None: ...
    def onRequestLogin(
        self, loginName: str, password: str, clientType: int, datas: bytes
    ) -> Any: ...
    def onLoseLogin(self, loginName: str) -> None: ...
    def onLoginCallbackFromDB(
        self, loginName: str, accountName: str, errorno: int, datas: bytes
    ) -> None: ...
    def onRequestCreateAccount(
        self, accountName: str, password: str, datas: bytes
    ) -> Any: ...
    def onCreateAccountCallbackFromDB(
        self, accountName: str, errorno: int, datas: bytes
    ) -> None: ...

class InterfacesModuleHooks(Protocol):
    def onInterfaceAppReady(self) -> None: ...
    def onTick(self, timerID: int) -> None: ...
    def onInterfaceAppShutDown(self) -> None: ...
    def onRequestCreateAccount(
        self, registerName: str, password: str, datas: bytes
    ) -> Any: ...
    def onRequestAccountLogin(
        self, loginName: str, password: str, datas: bytes
    ) -> Any: ...
    def onRequestCharge(
        self, ordersID: str, entityDBID: int, datas: bytes
    ) -> Any: ...

class DBMgrModuleHooks(Protocol):
    def onDBMgrReady(self) -> None: ...
    def onTick(self, timerID: int) -> None: ...
    def onDBMgrShutDown(self) -> None: ...
    def onReadyForShutDown(self) -> bool: ...
    def onSelectAccountDBInterface(self, accountName: str) -> str: ...

class LoggerModuleHooks(Protocol):
    def onLoggerAppReady(self) -> None: ...
    def onLoggerAppShutDown(self) -> None: ...
    def onReadyForShutDown(self) -> bool: ...
    def onLogWrote(self, logData: Any) -> None: ...

class BotsModuleHooks(Protocol):
    def onInit(self, isReload: bool) -> None: ...
    def onStart(self) -> None: ...
    def onFinish(self) -> None: ...

class BaseEntityHooks(Protocol):
    def onCreateCellFailure(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onGetCell(self) -> None: ...
    def onLoseCell(self) -> None: ...
    def onPreArchive(self) -> None: ...
    def onRestore(self) -> None: ...
    def onTimer(self, timerHandle: int, userData: int) -> None: ...
    def onWriteToDB(self, cellData: Any) -> None: ...

class ProxyHooks(Protocol):
    def onClientDeath(self) -> None: ...
    def onClientGetCell(self) -> None: ...
    def onClientEnabled(self) -> None: ...
    def onGiveClientToFailure(self) -> None: ...
    def onLogOnAttempt(self, ip: str, port: int, password: str) -> int: ...
    def onStreamComplete(self, id: int, success: bool) -> None: ...

class CellEntityHooks(Protocol):
    def onDestroy(self) -> None: ...
    def onEnteredView(self, entity: Entity) -> None: ...
    def onGetWitness(self) -> None: ...
    def onLoseWitness(self) -> None: ...
    def onMove(self, controllerID: int, userData: int) -> None: ...
    def onMoveOver(self, controllerID: int, userData: int) -> None: ...
    def onMoveFailure(self, controllerID: int, userData: int) -> None: ...
    def onRestore(self) -> None: ...
    def onSpaceGone(self) -> None: ...
    def onTurn(self, controllerID: int, userData: int) -> None: ...
    def onTeleport(self) -> None: ...
    def onTeleportFailure(self) -> None: ...
    def onTeleportSuccess(self, nearbyEntity: Entity) -> None: ...
    def onTimer(self, timerHandle: int, userData: int) -> None: ...
    def onUpdateBegin(self) -> None: ...
    def onUpdateEnd(self) -> None: ...
    def onWitnessed(self, isWitnessed: bool) -> None: ...
    def onWriteToDB(self) -> None: ...
