#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HEADER_PATH = ROOT / "kbe" / "src" / "lib" / "server" / "server_errors.h"
DEFAULT_OUTPUT_PATH = ROOT / "typings" / "_KBEngine_server_errors.pyi"

DEFINE_PATTERN = re.compile(
    r"^#define\s+(SERVER_(?:SUCCESS|ERR_[A-Z0-9_]+|ERR_MAX))\s+(\d+)\b",
    re.MULTILINE,
)
ARRAY_BLOCK_PATTERN = re.compile(
    r"const char SERVER_ERR_STR\[\]\[256\]\s*=\s*\{(?P<body>.*?)\};",
    re.DOTALL,
)
ARRAY_NAME_PATTERN = re.compile(r'"(SERVER_(?:SUCCESS|ERR_[A-Z0-9_]+))"')


@dataclass(frozen=True)
class ErrorConstant:
    name: str
    value: int


def parse_header(header_path: Path) -> list[ErrorConstant]:
    text = header_path.read_text(encoding="utf-8", errors="replace")

    constants = [ErrorConstant(match.group(1), int(match.group(2))) for match in DEFINE_PATTERN.finditer(text)]
    if not constants:
        raise ValueError(f"未在头文件中找到 SERVER_ERR 常量定义: {header_path}")

    array_match = ARRAY_BLOCK_PATTERN.search(text)
    if array_match is None:
        raise ValueError(f"未在头文件中找到 SERVER_ERR_STR 数组: {header_path}")

    runtime_names = ARRAY_NAME_PATTERN.findall(array_match.group("body"))
    if not runtime_names:
        raise ValueError(f"未在 SERVER_ERR_STR 数组中解析出错误码名字: {header_path}")

    if constants[-1].name != "SERVER_ERR_MAX":
        raise ValueError("头文件中的最后一个错误码常量不是 SERVER_ERR_MAX")

    exported_constants = constants[:-1]
    exported_names = [constant.name for constant in exported_constants]
    if exported_names != runtime_names:
        raise ValueError(
            "头文件宏定义与 SERVER_ERR_STR 导出名字不一致，"
            f"宏定义={exported_names!r}, SERVER_ERR_STR={runtime_names!r}"
        )

    for index, constant in enumerate(exported_constants):
        if constant.value != index:
            raise ValueError(
                f"{constant.name} 的值为 {constant.value}，"
                f"但运行时导出值来自数组下标，应为 {index}"
            )

    max_constant = constants[-1]
    if max_constant.value != len(runtime_names):
        raise ValueError(
            f"SERVER_ERR_MAX={max_constant.value}，"
            f"但 SERVER_ERR_STR 长度为 {len(runtime_names)}"
        )

    return constants


def render_stub(constants: list[ErrorConstant], header_path: Path) -> str:
    lines = [
        "# This file is generated by tools/generate_kbengine_server_errors_stub.py.",
        f"# Source: {header_path.as_posix()}",
        "",
    ]

    for constant in constants:
        lines.append(f"{constant.name}: int = {constant.value}")

    lines.append("")
    return "\n".join(lines)


def write_output(output_path: Path, content: str, *, check: bool) -> int:
    existing = output_path.read_text(encoding="utf-8") if output_path.exists() else None
    if existing == content:
        print(f"SERVER_ERR stub 已是最新: {output_path}")
        return 0

    if check:
        print(f"SERVER_ERR stub 需要更新: {output_path}")
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"SERVER_ERR stub 已更新: {output_path}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="根据 KBEngine 的 server_errors.h 生成 _KBEngine_server_errors.pyi。",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=DEFAULT_HEADER_PATH,
        help="server_errors.h 路径。",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="生成的 .pyi 输出路径。",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="只检查目标文件是否过期，不写回文件。",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    header_path = args.header.resolve()
    if not header_path.exists():
        print(f"未找到 server_errors.h: {header_path}", file=sys.stderr)
        return 2

    try:
        constants = parse_header(header_path)
        content = render_stub(constants, header_path)
    except Exception as exc:
        print(f"生成 SERVER_ERR stub 失败: {exc}", file=sys.stderr)
        return 1

    return write_output(args.output.resolve(), content, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
